components:
  # $tag$ Request Bodies #
  requestBodies:
    post$resourceName$Body:
      description: A JSON object containing $resource$ information
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
    put$resourceName$Body:
      description: A JSON object containing $resource$ information
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
    patch$resourceName$Request:
      description: A JSON object containing $resource$ information
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
